services:
  mongo:
    image: mongo
    container_name: gnn_mongo
    restart: on-failure
    networks:
      - gnn_network

  mongo_dash:
    container_name: gnn_mongo_dash
    restart: on-failure
    image: mongo-express
    ports:
      - "8002:8002"
    networks:
      - gnn_network
    environment:
      - PORT=8002
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=hossara
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
      - ME_CONFIG_MONGODB_URL=mongodb://gnn_mongo:27017
    depends_on:
      - mongo

  backend:
    container_name: gnn_backend
    restart: on-failure
    build: ./backend
    ports:
      - "8081:8081"
      - "3002:3000"
    networks:
      - gnn_network
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - mongo_dash
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 14s
      retries: 5

  frontend:
    container_name: gnn_frontend
    restart: on-failure
    build: ./frontend
    network_mode: "service:backend"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy

networks:
  gnn_network:
    name: gnn_network